# Generated by Django 5.1 on 2024-09-01 16:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='uploads'), upload_to='')),
            ],
        ),
    ]
